In [7]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 21 ms


In [9]:
%time for _ in range(10): my_list2 = my_list * 2

Wall time: 156 ms


In [10]:
data = np.random.randn(2, 3)

In [11]:
data

array([[-0.8905588 ,  0.09992483,  0.34264418],
       [-1.56879519, -0.67787942, -0.92387568]])

In [12]:
data*10

array([[ -8.90558804,   0.99924833,   3.42644179],
       [-15.68795186,  -6.77879421,  -9.23875684]])

In [13]:
data + data

array([[-1.78111761,  0.19984967,  0.68528836],
       [-3.13759037, -1.35575884, -1.84775137]])

In [14]:
data.shape # 用来表征数组每一维度的数量

(2, 3)

In [15]:
data.dtype # 描述数组的数据类型

dtype('float64')

In [16]:
data1 = [6, 7.5, 8, 0, 1]
np.array(data1)

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
data2 = [[1, 2, 3],[4, 5, 6]]

In [23]:
arr2 = np.array(arr2)

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 3)

In [26]:
arr2.dtype

dtype('int32')

In [27]:
data3 = [["小明"], ["小强"], ["小红"]]

In [28]:
arr3 = np.array(data3)

In [29]:
arr3

array([['小明'],
       ['小强'],
       ['小红']], dtype='<U2')

In [30]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30,)])

In [31]:
print(a)

[[10]
 [20]
 [30]]


In [32]:
a = (10)

In [33]:
a

10

In [34]:
type(a)

int

In [35]:
b = (10,)

In [36]:
type(b)

tuple